site_name: 英语自学指南
site_author: InsideEmpire

repo_name: english-self-learning
repo_url: https://github.com/InsideEmpire/english-self-learning/

theme:
  name: material
  language: zh

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto Slab
    code: Roboto Mono


nav:
  - 首页: index.md
  - 平台:
      - BBC Learning English: 平台/BBC Learning English.md
  - 书籍:
      - Illustrated Maths Dictionary: 书籍/illustrated maths dictionary.md
  - 播客:
      - Luke's ENGLISH Podcast: 播客/Luke's ENGLISH Podcast.md
